SELECT DISTINCT 
[SHP_NM]
      ,TNT.[SERVICE]  AS SERVICE
      ,TNT.[DEST_ZIP] AS DESTZIP,
	  TNT.[ORIG_ZIP] AS ORIGZIP
,[TM_IN_XIT] AS TNT

,ZN.[ZN] AS Zone

into [UPS ZONES].[dbo].[TNT11]
  FROM [UPS ZONES].[dbo].[US-DC-TNT-DATA] AS TNT
 , [UPS ZONES].[dbo].[US-RegionalCarriers-Zone-Data] AS ZN

WHERE 
 TNT.[SERVICE]=ZN.[SERVICE]
AND TNT.DEST_ZIP = ZN.DEST_ZIP
AND TNT.ORIG_ZIP = ZN.ORIG_ZIP